---
language: python
services: docker
python:
  - "2.7"
  - "3.6"

install:
  # Install requirements.
  - sudo apt-get install python-apt
  - pip install ansible
  - pip install -r ansible-requirements.txt

  # Install ansible-container from source.
  # - git clone https://github.com/ansible/ansible-container.git
  # - cd ansible-container
  # - pip install -e .[docker]
  # - cd ..

  # Install ansible-container from pip.
  - pip install ansible-container[docker]

script:
  - set -e

  # Build the two images locally.
  - cd prebuild
  - ansible-galaxy install -r requirements.yml --force
  - ansible-playbook -i 'localhost,' -c local -e ansible_python_interpreter=/usr/bin/python -e prebuild_test_mode=True prebuild.yml

  # Build all the containers with Ansible Container.
  - cd ..
  - ansible-container --debug --var-file config.yml build

  # Test the Docker Compose file.
  - docker-compose up -d

  - set +e

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
