apiVersion: v1
kind: Service
metadata:
  name: bastion
  namespace: bastions
spec:
  type: NodePort
  selector:
    k8s-app: bastion
  ports:
  - port: 22
    targetPort: 22
    nodePort: 2222
    protocol: TCP
    name: ssh
