#!/bin/bash

#!/bin/sh
output=${2:-png}
for i in $(ls -1 /mnt/src/*.mmd)
do
  echo "building $i.$output"
  mermaid  -t /usr/local/lib/node_modules/mermaid/dist/mermaid.forest.css -p $i
  cp -v $i.png /mnt/out/
done
