# https://github.com/krish143434/fluentd-es-proxy                                                                                                                                                                                   [49/16514]
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
  name: fluentd-elasticsearch
  namespace: logging
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        kubernetes.io/cluster-service: "true"
      name: fluentd-elasticsearch
      namespace: logging
    spec:
      containers:
        - env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ELASTICSEARCH_URL
              value: "https://my_es_endpoint"
            - name: AWS_ACCESS_KEY_ID
              value: "my_aws_access_key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "my_aws_secret_key"
            - name: FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH
              value: "128" #maintain this or else there may be a chance of buffer issues
            - name: LOGSTASH_PREFIX
              value: fluentd # use a prefix for your index pattern in kibana
            - name: LOGSTASH_DATEFORMAT
              value: '%Y.%m.%d' #time format, if you remove it will take empty
          image: nicolasvion/fluentd-es-proxy:v0.1
          imagePullPolicy: IfNotPresent
          name: fluentd-elasticsearch
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/td-agent/conf.d/
              name: fluentd-config

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - name: fluentd-config
          configMap:
            name: fluentd-config

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: logging
