apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-logging
  ports:
    - port: 24224
      targetPort: 24224
      protocol: TCP
      name: fluentd
