#!/bin/sh
output=${2:-pdf}
echo "building $1.$output"
exec /usr/local/bin/pandoc \
  --toc \
  --pdf-engine pdflatex  \
  --template /templates/eisvogel.template \
  --listings \
  --variable mainfont="Muli" \
  --variable geometry:margin=1in \
  --highlight-style zenburn \
  --variable date=$DATE \
  -f markdown \
  --to=latex \
  -o /mnt/out/$1.$output \
  /mnt/src/*.md
