#!/bin/sh

# Written by: Keefer Rourke <https://krourke.org>
# Based on AUR package <https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-google-fonts-git>

srcdir="/tmp/google-fonts"
pkgdir="/usr/share/fonts/truetype/google-fonts"
giturl="https://github.com/google/fonts.git"

apt-get update
apt-get install -y unzip curl
curl -sLo /tmp/muli.zip https://fonts.google.com/download?family=Muli
mkdir -p /usr/share/fonts/truetype/muli
cd /usr/share/fonts/truetype/muli
unzip /tmp/muli.zip
rm -f /tmp/muli.zip
apt-get remove --purge -y unzip curl
rm -rf /var/cache/apt/*
